### ISSUE TITLE
Implement Framework and all Test cases for 3botLogin app

### ISSUE THREAD

**Issue by john-kheir** [john-kheir/3botloginapp#1]
- This Story is created to track all the test cases that can be automated for 3botLogin app.
- These tasks should for now cover testing the app on Android platform.
- **Appium** will be used as the main framework to automated this test cases with all the required dependencies .

#### Here are the tasks that need to be completed 
- [ ] Implement a basic Framework #2 
   
- [ ] Test Case: A Registered user can login using the mobile-only flow #3 
- [ ] Test Case: A user registers using the mobile-only flow #4
- [ ] Test Case: Check on preferences page main info #5
- [ ] Test Case: Remove account from device #6
